quarkus:
  resteasy:
    path: "/authorization"
  http:
    port: 8081
  log:
    console:
      json: false
#        pretty-print: true
#        date-format: "YYYY-MM-dd HH:mm:ss"
#        exception-output-type: "detailed-and-formatted"
