apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/app-root: /api
spec:
  tls:
    - secretName: testsecret-tls
  rules:
    - http:
        paths:
          - path: /api/(.*)
            backend:
              serviceName: java-greeting-service
              servicePort: 80
